version: '3'
services:
  backend:
    build: ./MoviePlatform_Backend
    image: movie_platform_backend_davidmb:1.0
    working_dir: /app
    ports:
      - "30000:8000"
    volumes:
      - "./MoviePlatform_Backend/:/app"
    networks:
      - moviePlatformNet
  frontend:
    image: httpd:alpine3.20
    ports: 
      - "30080:80"
    volumes:
      - "./MoviePlatform_Frontend/dist/:/usr/local/apache2/htdocs/"
    networks:
      - moviePlatformNet
  mongoDB:
    # image: mongodb/mongodb-community-server:7.0-ubi8
    image: mongo:8.0.0-rc13-jammy
    ports:
      - "30017:27017"
    volumes:
      - "./db/:/data/db"
    networks:
      - moviePlatformNet
    command: mongod

networks:
  moviePlatformNet:
    driver: bridge
